### PR TITLE
Added all dependencies

### LINKED ISSUE #22: Update to install dependencies
Update pyproject to include all other package

### PR DESCRIPTION
**Pull request by s-voon**
Added pandas, tabulate, scikit-learn, pytest and pytest-cov dependencies. Lmk if there is anything is missing!

### CODE REVIEW

**Comment by zgarciaj** [comment]
Thank you, Sharon!

I've reviewed the dependencies, and it seems the only potential missing component might be numpy, which I believe is required by the fit function.

**Comment by s-voon** [comment]
Thanks for reviewing Zeily! I think that numpy is part of the pandas package

**Comment by zgarciaj** [comment]
Oh my bad! You are right! Thank you!

**Review by AReyH — APPROVED** [review]
LGTM

**Pull request merged**
