### PR TITLE
fix: Feedback addressed by Anu for function display_best_score

### LINKED ISSUE #71: Feedback point - display_best_score
I will be updating display_best_score function with corresponding test.

### PR DESCRIPTION
**Pull request by AnuBanga**
Hi @zgarciaj, I have made changes in display_best_score functionto fix feedback point. Kindly review it and in case of any issue, do let me know. Thanks

### CODE REVIEW

**Comment by AnuBanga** [comment]
@zgarciaj I have made changes in same test for different scoring metrics. What do you suggest, should I create separate test for  R2 scoring metric?

**Review by zgarciaj — CHANGES_REQUESTED** [review]
Hi @AnuBanga,

Fantastic job on this pull request! I've reviewed the changes and would like to suggest a few adjustments to enhance the overall quality:

1. **test_bestscore.py:**
   - In the `test_existing_scoring_metric` method, I noticed that `expected_output` is defined twice for different metrics ('MAE' and 'R2'). This might cause confusion or errors since the final assertion checks only the last assignment (for 'R2'). To clarify, it would be beneficial to divide this into two distinct test cases, each dedicated to a specific metric. For example, you could use `pd.testing.assert_frame_equal(result_2, expected_output_2)` for the second metric. I recommend, beyond running pytest, verifying that each commit is passing the CI/CD checks🤠

2. **bestscore.py:**
   - (Optional) Regarding the docstring example: It currently demonstrates that a `ValueError` is raised for an unrecognized metric ('R2'). That is correct given the input of your example. However, considering that bestscore is expected to be followed by the fit function which includes the R2 metric, we might avoid confusion by using a different metric (like 'F1 Score') in this example. This point is highly optional as your example is very much correct.

Hope these suggestions help!

**Comment by zgarciaj** [comment]
> @zgarciaj I have made changes in same test for different scoring metrics. What do you suggest, should I create separate test for R2 scoring metric?

Apologies for the delayed response. Per my review, I agree that it is a good idea to separate the tests for metrics favoring lower values from those favoring higher values.

**Comment by AnuBanga** [comment]
@zgarciaj I made changes as suggested in second point. Thanks for suggestion as docstring was not showing correct information and wrong model/value was being used.

**Comment by AnuBanga** [comment]
@zgarciaj I have made changes to include separate test for scoring metric R2. Please review it.
Also, verified ci cd was successful with each commit.

**Review by zgarciaj — APPROVED** [review]
Hi @AnuBanga !
Everything appears to be in excellent shape! I would recommend a small enhancement: clarify in the docstring for test_existing_scoring_metric_R2() that it is focused on testing the R2 metric. Using precise docstrings is beneficial as it aids in clearly distinguishing between different tests, making the code more user-friendly and easier to understand.

Other than that, I believe this branch is good for merger!

**Pull request merged**
