### PR TITLE
Example File

### LINKED ISSUE #49: Example File
After each person has incorporated the narrative of their specific function into their branch, I will proceed to consolidate everything into the merged_example_file branch.

After completion, we will verify that it has been successfully uploaded to Read the Docs, ensuring that our readme accurately displays our new logo on the site. Subsequently, we will incorporate a link to our Read the Docs page into our readme.

### LINKED ISSUE #55: Unnecessary File Deleted
Based on the feedback regarding the first milestone, the file autopredictor.py has been removed.

### PR DESCRIPTION
**Pull request by zgarciaj**
This branch contains all the vignettes merged onto one example file.

### CODE REVIEW

**Comment by zgarciaj** [comment]
@AnuBanga, I have completed the proofreading and formatting of the example file. I would greatly appreciate any feedback you may have!

**Comment by zgarciaj** [comment]
@AnuBanga, I have completed the proofreading and formatting of the example file. I would greatly appreciate any feedback you may have!

**Review by AnuBanga — COMMENTED** [review]
Well done.. It is a great compilation @zgarciaj
Only issue I find is that it is displaying a warning 
/Users/zeily/miniconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn( 
This should not visible on rendered file, specially with local folder name.

**Comment by zgarciaj** [comment]
Hi @AnuBanga, great observation! Could you possibly execute the notebook on your end? I'm curious to see if the warning appears for you as well. If it doesn't, would you mind committing the newly rendered version? Thanks!

**Comment by zgarciaj** [comment]
@AnuBanga, the warning appears in the section for the fit function, which will be handled by @AReyH. @AReyH, could you ensure that when you add your section and render it it does not display any warnings? If any arise, they might be resolved by setting SVC(dual=True) or using from sklearn.exceptions import FutureWarning

**Comment by AnuBanga** [comment]
> Hi @AnuBanga, great observation! Could you possibly execute the notebook on your end? I'm curious to see if the warning appears for you as well. If it doesn't, would you mind committing the newly rendered version? Thanks!

I have tried rendering on my laptop. But I am getting the same warning.

**Comment by AReyH** [comment]
I added the warning filter in order to not get the warning! We can either stick with this or add the `dual` parameter to the SVC function. @zgarciaj

**Comment by zgarciaj** [comment]
I believe incorporating the warning filter is an excellent decision. Thank you, @AReyH! 

I will run it once again and commit the rendered version. I think we would be good to merge after that!

**Comment by zgarciaj** [comment]
I have rendered the last version. @AnuBanga I think we are good for merger!

**Review by AnuBanga — APPROVED** [review]
Changes look good. We are good for merging

**Pull request merged**
